### ISSUE TITLE
Support all Node.js Tier1 platforms, partial support Tier2/Experimental platforms

### ISSUE THREAD

**Issue by Brooooooklyn** [Brooooooklyn/canvas#110]
https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms

# Tier1
- [x] x86_64-unknown-linux-gnu
- [x] x86_64-pc-windows-msvc
- [x] x86_64-apple-darwin
- [x] armv7-unknown-linux-gnueabihf
- [x] aarch64-unknown-linux-gnu

# Tier2
No

# Experimental

- [x] aarch64-linux-android
- [x] aarch64-apple-darwin
- [x] x86_64-unknown-linux-musl

**Comment by StringKe** [comment]
Can it support wasm, such as compiling with emscripten

**Comment by Brooooooklyn** [comment]
No, I'm using `napi-rs` to implement this library, this is a NodeJS `N-API` abstraction, it can't be compiled into wasm.

wasm support should be tracked in https://github.com/rust-skia/rust-skia/issues/39
