### ISSUE TITLE
TextMetrics support plan

### ISSUE THREAD

**Issue by doodlewind** [Brooooooklyn/canvas#156]
For the `measureText` API in roadmap, here are all the required properties to support:

* [ ] actualBoundingBoxAscent
* [ ] actualBoundingBoxDescent
* [ ] actualBoundingBoxLeft
* [ ] actualBoundingBoxRight
* [ ] alphabeticBaseline
* [ ] emHeightAscent
* [ ] emHeightDescent
* [ ] fontBoundingBoxAscent
* [ ] fontBoundingBoxDescent
* [ ] hangingBaseline
* [ ] ideographicBaseline
* [ ] width

I may look into #125 and file a new PR implementing `TextMetrics` soon. @Brooooooklyn please let me know if you have other timeframe about this part.

**Comment by Brooooooklyn** [comment]
I was originally intending to use `cssparser` to implement font rule parsing in https://github.com/Brooooooklyn/skia-rs/pull/125, but then I realized that `Regexp` would be enough for parsing `font style` string.

So the `Font::new` method should be totally rewrite by `Regexp` implementation, and I may not have time to do this for the next two weeks.

**Comment by Brooooooklyn** [comment]
I think we can start this since this https://github.com/Brooooooklyn/skia-rs/pull/125 merged.

**Comment by doodlewind** [comment]
Great work! I have some time this month, let me get familiar with current code base first.

**Comment by doodlewind** [comment]
Here's what we need for a minimal working demo:

* Using [SkTypeface](https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkTypeface.html) to load font files.
* Getting [SkFont](https://api.skia.org/classSkFont.html#aadddf8b6ab5c54b69a46ae2704a2e713) with SkTypeFace and font size, which is ready to draw.
* Using [SkFont::getMetrics](https://api.skia.org/classSkFont.html#aadddf8b6ab5c54b69a46ae2704a2e713) to get TextMetrics.
* Adding non-standard JS API for registering custom fonts.

The C++ part basically works in this way:

``` cpp
auto typeface = SkTypeface::MakeFromFile("font/Roboto-Regular.ttf");
auto font_size = 16;
auto hello = "hello";
SkFont font(typeface, font_size);
SkPaint paint;
canvas->drawSimpleText(hello, strlen(hello), SkTextEncoding::kUTF8, x, y, font, paint);
```

And for the extended JS part, here is my proposal (somewhat close to [FontLibrary](https://github.com/samizdatco/skia-canvas#fontlibrary) in skia-canvas):

``` js
import { GlobalFonts } from '@napi-rs/canvas'

// all methods are static with global effect
GlobalFonts.register('Comic Sans', ['fonts/comic-sans.ttf'])
GlobalFonts.families // ['serif', 'Comic Sans']
```

API:

``` ts
interface Typeface {
  family: string // 'Times New Roman'
  weights: number[] // [100, 400, 600]
  styles: string[] // ['normal', 'italic']
}

interface GlobalFonts {
  readonly families: string[]
  query(family: string): Typeface
  has(family: string): boolean
  register(family: string, paths: string[]): void
}
```

@Brooooooklyn let me know if you have any ideas about this :)
