### ISSUE TITLE
Rust toolchain config looks too aggressive

### ISSUE THREAD

**Issue by doodlewind** [Brooooooklyn/canvas#213]
The `rust-toolchain` file is now set to `nighty`, while it may not ensure that all rust components can be successfully installed. According to the [rustup components history](https://rust-lang.github.io/rustup-components-history/x86_64-apple-darwin.html), `rls` is missing in builds in recent two days, leading to the [rls unavailable issue](https://github.com/rust-lang/rls#error-component-rls-is-unavailable-for-download-nightly) that prevents VSCode doing IntelliSense. For now I config the `rust-toolchain` to `nightly-2021-03-25` locally to workaround this issue, but I'm wondering if we have enough reason not to use stable rust toolchain?

**Comment by Brooooooklyn** [comment]
Cargo profile.strip = "symbol" is a nightly feature, and we need it to make the binary smaller: https://github.com/Brooooooklyn/canvas/blob/main/Cargo.toml#L30

I will pin the rust-toolchain to the latest usable version.
