### ISSUE TITLE
Extends Path2D to match PathKit functions

### ISSUE THREAD

**Issue by Brooooooklyn** [Brooooooklyn/canvas#227]
https://skia.org/docs/user/modules/pathkit/

/cc @yisibl

**Comment by yisibl** [comment]
Nice!

**Comment by yisibl** [comment]
当前 Skia 官方的 pathkit 没有导出 `asWinding()` 函数，希望也可以增加这个 API。它在字体处理中非常有用，可以把 `fill-rule` 由 `nonzero` 转换为 `evenodd`。

**Comment by yisibl** [comment]
Skia 的实现在这里：https://bugs.chromium.org/p/skia/issues/detail?id=7682#c5

**Comment by yisibl** [comment]
这个 .NET 库中有类似的导出：https://github.com/mono/SkiaSharp/issues/840

**Comment by OpenGG** [comment]
@yisibl

**Comment by OpenGG** [comment]
[asWinding()](https://github.com/google/skia/blob/main/src/pathops/SkPathOpsAsWinding.cpp) 完成度不如 [skia-pathops](https://github.com/fonttools/skia-pathops/blob/746870053357a6457ceedfe8a3a159152272619c/src/python/pathops/_pathops.pyx#L1170)
现在还无法完全摆脱 python 的代码

**Comment by OpenGG** [comment]
抱歉，是我搞错了。

[asWinding()](https://github.com/google/skia/blob/main/src/pathops/SkPathOpsAsWinding.cpp) 目前只能处理没有交叉点的 path ，这是一个已知问题，不能算bug，起码不是下游skr canvas的bug。

> Set the result with fill type winding to area equivalent to path.
> Returns true if successful. Does not detect if path contains contours which contain self-crossings or cross other contours; in these cases, may return true even though result does not fill same area as path.
> Returns true if operation was able to produce a result; otherwise, result is unmodified. The result may be the input.

Demo: 

https://codesandbox.io/s/github/OpenGG/evenodd-fix-winding?file=/src/App.vue

**Comment by yisibl** [comment]
@OpenGG 印象中，我记得 skia-pathops 对于 `asWinding()`  做过一些特殊处理

**Comment by OpenGG** [comment]
@yisibl 
是的，skia-canvas 和 skr-canvas 都直接使用了 skia 的 asWinding() ，都不能处理交叉点。
skia-pathops 在 python 里有一个特殊处理，所以可以得到正确结果。
