### ISSUE TITLE
ctx.filter

### ISSUE THREAD

**Issue by Snowflake107** [Brooooooklyn/canvas#249]
In typescript typings, `ctx.filter` is available but does not work when used.

> In mdn docs, it is marked as `Experimental`

Docs: **[https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter)**

**Comment by Brooooooklyn** [comment]
Move to https://github.com/Brooooooklyn/canvas/issues/246
