### ISSUE TITLE
fillText crashes on Windows

### ISSUE THREAD

**Issue by doodlewind** [Brooooooklyn/canvas#253]
Following error messages are raised when calling `fillText` on Windows:

```
$ node example/text.js
SkIcuLoader: datafile missing: C:\Program Files\nodejs\icudtl.dat
SkIcuLoader: datafile missing: \\?\C:\Users\ewind\Desktop\code\canvas\icudtl.dat
Segmentation fault
```

Providing `icudtl.dat` manually can fix this issue. This file contains [ICU locales](https://unicode-org.github.io/icu/userguide/icu_data/buildtool.html#overview-what-is-in-the-icu-data-file) and is [specially handled by Skia on Windows](https://chromium.googlesource.com/skia/+/master/third_party/icu/SkLoadICU.cpp#6). By default the `out/Static/icudtl.dat` is generated with Skia build, to my understanding this file needs to ship in the same path with the `skia.win32-x64-msvc.node`.

**Comment by sunshaobin** [comment]
meet this problem when calling fillText on Windows

PS C:\Users\HCKJ\Desktop\canvas-test> node index.js
SkIcuLoader: datafile missing: C:\Program Files\nodejs\icudtl.dat.
SkIcuLoader: datafile missing: \\?\C:\Users\HCKJ\Desktop\canvas-test\node_modules\@napi-rs\canvas-win32-x64-msvc\icudtl.dat.
PS C:\Users\HCKJ\Desktop\canvas-test>

**Comment by Brooooooklyn** [comment]
Try install @napi-rs/canvas-icudtl-win32-x64

**Comment by Tsuk1ko** [comment]
> Try install @napi-rs/canvas-icudtl-win32-x64

Still got same error in latest version, whether @napi-rs/canvas-icudtl-win32-x64 is installed or not.

**Comment by Brooooooklyn** [comment]
@Tsuk1ko Tested on my windows, it just printed  a warning `SkIcuLoader: datafile missing: C:\Program Files\nodejs\icudtl.dat.`, but program worked as expect, with the version `@napi-rs/canvas@0.1.5`
