### ISSUE TITLE
fillText not working

### ISSUE THREAD

**Issue by talentlessguy** [Brooooooklyn/canvas#319]
Hello, thanks for creating this library! It's much less painful to use than node-canvas because it doesn't work on new Node.js versions...

At the moment I'm facing a little issue with canvas. Even though `fillText` has been added to canvas already, it doesn't seem to be working for me.

This is the code:

```ts
import { createCanvas } from '@napi-rs/canvas'
import fs from 'fs/promises'
import path from 'path'

const canvas = createCanvas(1000, 1000)

const ctx = canvas.getContext('2d')

ctx.fillStyle = 'red'
ctx.font = '30px Noto Serif'
ctx.textAlign = 'center'
ctx.fillText('Hello World', 500, 500)

export function generateImage(title: string) {
  try {
    return canvas.encode('png')
  } catch (e) {
    console.log('Failed to encode image: ' + e.message)
    throw e
  }
}
```

and this is what I get:

![test](https://user-images.githubusercontent.com/35937217/126763069-dc12106c-e433-462e-90d2-77e4aab611dd.png)

## System info

- Node.js 16.5.0
- Linux 5.10.49-1-MANJARO
- `@napi-rs/canvas` 0.0.12

## Additional context

`skia-canvas` seems to work fine

**Comment by Brooooooklyn** [comment]
I have not implement the "preload system fonts" features because this library doesn't depend on `fontconfig`. I will implement it in https://github.com/Brooooooklyn/canvas/pull/265 . For now you can load font manually like: https://github.com/Brooooooklyn/canvas/blob/70fd0491c2d106b9ae028c4d233557f5ad3738e4/draw-text.js#L11

**Comment by Brooooooklyn** [comment]
**preload system fonts** has been done, it should work fine now.
