### ISSUE TITLE
Get the width and height from the viewBox

### ISSUE THREAD

**Issue by yisibl** [Brooooooklyn/canvas#330]
When the read SVG file does not have width/height, the width and height should be obtained from the viewBox.

```svg
<svg viewBox="0 0 300 300" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect fill="#2498EE" x="0" y="0" width="300" height="300"></rect>
    </g>
</svg>
```

Of course, I think the final solution still needs to get the BBox of SVG. The width and height of the generated picture can be set safely and freely through BBox.

**Comment by yisibl** [comment]
It looks like it needs to be processed here
https://github.com/Brooooooklyn/canvas/blob/cc2e0ddf0f8ac09669965a5d4434660ad08cdcd7/src/image.rs#L175-L182

**Comment by yisibl** [comment]
This SVG rendering error https://iconfont.alicdn.com/s/3f4934e1-bb85-41ac-87bd-4d917952c6c1_origin.svg

![image](https://user-images.githubusercontent.com/2784308/127809636-50305095-2f31-4295-9f97-f08e1a4879d6.png)

**Comment by Brooooooklyn** [comment]
> This SVG rendering error https://iconfont.alicdn.com/s/3f4934e1-bb85-41ac-87bd-4d917952c6c1_origin.svg

I think skia doesn't support inline css for SVG for now.
