### ISSUE TITLE
toDataURL() should not be url safe base64

### ISSUE THREAD

**Issue by Tsuk1ko** [Brooooooklyn/canvas#344]
https://github.com/Brooooooklyn/canvas/blob/a2bd4556100524120cf4d530ac309e20a52cc6aa/src/lib.rs#L291

https://github.com/Brooooooklyn/canvas/blob/a2bd4556100524120cf4d530ac309e20a52cc6aa/src/lib.rs#L385

**Comment by Brooooooklyn** [comment]
Should be fixed in https://github.com/Brooooooklyn/canvas/pull/343
