### ISSUE TITLE
[Feature request] Support font family name with spaces

### ISSUE THREAD

**Issue by Tsuk1ko** [Brooooooklyn/canvas#345]
For example:

```js
// GlobalFonts.registerFromPath('path/to/font', 'Microsoft YaHei');

ctx.font = '100px "Microsoft YaHei"';
// or
ctx.font = "100px 'Microsoft YaHei'";
```

--------

By the way, is there a way to remove warning `SkIcuLoader: datafile missing: xxx\icudtl.dat.`?

**Comment by Brooooooklyn** [comment]
> By the way, is there a way to remove warning SkIcuLoader: datafile missing: xxx\icudtl.dat.

I will remove it in next release.

**Comment by Brooooooklyn** [comment]
`SkIcuLoader: datafile missing: xxx\icudtl.dat.` warning will be removed in https://github.com/Brooooooklyn/canvas/pull/347
