### ISSUE TITLE
v0.1.7 got "Illegal instruction" error on linux amd64

### ISSUE THREAD

**Issue by Tsuk1ko** [Brooooooklyn/canvas#357]
![image](https://user-images.githubusercontent.com/24877906/133917506-8186309a-c73f-4460-8b03-deaa29814f11.png)

It seems that there is a problem with dependency compatibility judgement?

**Comment by Brooooooklyn** [comment]
0.1.7 shipped with `avx2` instruction requirement for performance: https://github.com/Brooooooklyn/canvas#x64

Which CPU model you have?

**Comment by Tsuk1ko** [comment]
Here is my cpuinfo:

![image](https://user-images.githubusercontent.com/24877906/133917759-1d5370d9-c432-4ab0-bb2f-239e80684157.png)

It doesn't seem to support avx2...

**Comment by Tsuk1ko** [comment]
Can a compatible version be provided for cpus don't support avx2?

**Comment by Brooooooklyn** [comment]
Okay, please downgrade to 0.1.6 for now, I will change the compile option to support back old CPU in next release.
