### ISSUE TITLE
textAlign is not working

### ISSUE THREAD

**Issue by ThisNils** [Brooooooklyn/canvas#376]
SKRSContext2D#textAlign is not working correctly. "right" and "center" seem to position the text relative to the right border of the canvas (examples below). "left" made the text completely disappear.

Example 1:
```js
ctx.textAlign = 'center';
ctx.fillText('CENTERED TEXT', canvas.width / 2, canvas.height / 2);
```
Output:
<img src="https://cdn.discordapp.com/attachments/756784147468648478/901422063485583380/out.png" width=400>

Example 2:
```js
ctx.textAlign = 'right';
ctx.fillText('CENTERED RIGHT TEXT', canvas.width / 2, canvas.height / 2);
```
Output:
<img src="https://cdn.discordapp.com/attachments/756784147468648478/901422558442815559/out.png" width=400>

**Versions:**
NodeJS: v16.11.1
@napi-rs/canvas: v0.1.13

**Comment by zkwolf** [comment]
👀

**Comment by Brooooooklyn** [comment]
I'm busy on napi-rs 2.0 now, I'll back to this project in the next year.

**Comment by ThisNils** [comment]
A workaround would be
```ts
const fillTextCentered = (ctx: SKRSContext2D, text: string, x: number, y: number) => {
  const { width } = ctx.measureText(text);
  ctx.fillText(text, x + width / 2, y);
};
