### ISSUE TITLE
emoji measureText width wrong when diff font-family

### ISSUE THREAD

**Issue by nxg916** [Brooooooklyn/canvas#400]
```
 context.font = '12px Arial';
 const result = context.measureText('😢');
```
 emoji width is 8

```
context.font = '12px PingFang';
const result = context.measureText('😢');
```
emoji width is 12

**Comment by Brooooooklyn** [comment]
@nxg916 

```js
context.font = '12px Arial';
const result = context.measureText('😢');
```

What graphic actually rendered by this font?

**Comment by nxg916** [comment]
> @nxg916
> 
> ```js
> context.font = '12px Arial';
> const result = context.measureText('😢');
> ```
> 
> What graphic actually rendered by this font?

const registerEmpji = GlobalFonts.registerFromPath('./AppleColorEmoji.ttc', 'Apple Emoji');

**Comment by Brooooooklyn** [comment]
@nxg916 Try the latest version, maybe it was fixed
