### ISSUE TITLE
Consume SVG

### ISSUE THREAD

**Issue by huozhi** [Brooooooklyn/canvas#402]
The `Image` seesm to support consuimg svg as data source, but didn't find any documentation for it.

I'm trying with the following code

```js
const image = new Image()
image.src = svg // svg string
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d')
ctx.drawImage(image, 0, 0, 200, 200)
const buffer = await canvas.encode('png')
```

And then I failed with `fer::Data(Local<v8::Value>): Assertion `val->IsArrayBufferView()' failed.` error.

* Is there any restrictions for using svg data source?
* Is `foreignObject` supported?

**Comment by Brooooooklyn** [comment]
> Is there any restrictions for using svg data source?

The `SVG` string must start with `<svg>`: https://github.com/Brooooooklyn/canvas/blob/main/src/image.rs#L344-L357

> Is foreignObject supported?

No. See https://github.com/google/skia/tree/main/modules/svg/include for all supported svg elements.

If you want to render a complex svg image on skr-canvas, you can use https://github.com/yisibl/resvg-js to rasterize it into pixels and put it into canvas.

**Comment by huozhi** [comment]
Thanks!
