### ISSUE TITLE
getImageData returns data inconsistent with node-canvas

### ISSUE THREAD

**Issue by kekeqy** [Brooooooklyn/canvas#406]
How to solve this problem?

**Comment by kekeqy** [comment]
The value returned by toDataURL is also inconsistent

**Comment by Brooooooklyn** [comment]
Please provide a minimal example to reproduce your issue

**Comment by kekeqy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by kekeqy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
