### ISSUE TITLE
Path isn't created if any of the `lineTo's` contain `NaN`, inconsistent against html canvas

### ISSUE THREAD

**Issue by MarosPistej** [Brooooooklyn/canvas#410]
## About
If any of the `lineTo(x,y)` of path receive `NaN` as coordinate value, whole path is't rendered, on the other hand html canvas just skip incorrect coordinates and try to draw path if possible

### Example
```js
// canvas width="300" height="150"
ctx.beginPath();
ctx.lineTo(NaN, 100);
ctx.lineTo(50, 50);
ctx.lineTo(100, NaN);
ctx.lineTo(250, 100);
ctx.stroke();
```
`html canvas`
![image](https://user-images.githubusercontent.com/43110161/150992567-3fd4669d-854e-460e-8fee-1f4c90219b58.png)

`@napi-rs/canvas`
![image](https://user-images.githubusercontent.com/43110161/150992666-e8ee6a94-1fc0-4b5d-973d-dc5a586add30.png)

**Comment by meloalright** [comment]
And it will crash if contain `undefined`

```javascript
ctx.lineTo(undefined, 100)
```
