### ISSUE TITLE
Memory leak of `text` & app crash on `encode('png')`

### ISSUE THREAD

**Issue by MarosPistej** [Brooooooklyn/canvas#412]
Discovered memory leak while drawing `text` and segmentation error app crash when `encoding`

I created minimum reproducible example repository here https://github.com/MarosPistej/napi-rs-canvas-text-mem-leak

**Comment by louisfoster** [comment]
I'm wondering if [`paragraph` ](https://github.com/Brooooooklyn/canvas/blob/main/skia-c/skia_c.cpp#L388)needs to have `reset()` called at the end? I'm not a pro at C++, so I'm just trying to understand the cause of the leak, but looking at [how paragraph is created](https://github.com/google/skia/blob/main/modules/skparagraph/src/ParagraphBuilderImpl.cpp#L160) it appears to use make_unique, which from my understanding is a kind of smarter/safer alternative to `new`. Although, [reading this SO question](https://stackoverflow.com/questions/25609457/does-unique-ptrrelease-call-the-destructor), it is pointed out that something created via make_unique should subsequently called `reset()` to free the memory. However, I noticed in the code in my first link, there's no call to reset.

**Comment by louisfoster** [comment]
I tried adding `delete paragraph;` to the end of the function and tried building again. I didn't notice any difference in the memory with my tests, too much memory still being used and not released. In fact I believe I was also incorrect earlier about encode not also having some kind of leak, but it could possibly be my code.
