### ISSUE TITLE
部署到linux系统后找不到 '@napi-rs/canvas-linux-x64-gnu'

### ISSUE THREAD

**Issue by 3338606790** [Brooooooklyn/canvas#419]
我是在mac上开发的，部署到阿里云函数后有这个错误， Cannot find module '@napi-rs/canvas-linux-x64-gnu'， 为什么，是因为开发安装了os版本的库，复制过去后这个库在另一个系统上不起作用吗？

**Comment by Brooooooklyn** [comment]
对的，如果你使用 `yarn` 可以安装的时候使用 `yarn install --ignore-platfom` 参数安装。
推荐你在 Docker 里面进行安装: `docker run --rm -it  -v $(pwd):/work -w work node:lts-slim yarn install`，这样既可以使用 lockfile 安装正确的依赖，又没有系统兼容问题。

注意: 这不是 canvas 和 NAPI-RS 的问题，只要你的项目有原生依赖 (C/C++/Rust 编写的库) 就不可以跨操作系统进行安装，否则就会出错。
