### ISSUE TITLE
The `globalCompositeOperation` configuration support is incomplete

### ISSUE THREAD

**Issue by erha19** [Brooooooklyn/canvas#424]
I have tried to use `@napi-rs/canvas` to mock `HTMLCanvasElement.prototype.getContext` like follows:

```js
const { createCanvas } = require('@napi-rs/canvas');
const canvas = createCanvas(1, 1);
jsdom.window.HTMLCanvasElement.prototype.getContext = canvas.getContext.bind(canvas);
```

But I have the following problem when using the `globalCompositeOperation` configuration support is not complete

![image](https://user-images.githubusercontent.com/9823838/154193625-246788d8-a076-4b93-8890-5839aa02585d.png)

The `copy` value is not supported, and it is use in `xterm.js`

ref: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by bytemain** [comment]
@Brooooooklyn Could you release a new version for this?

**Comment by Brooooooklyn** [comment]
@bytemain published https://github.com/Brooooooklyn/canvas/releases/tag/v0.1.21

**Comment by bytemain** [comment]
> @bytemain published https://github.com/Brooooooklyn/canvas/releases/tag/v0.1.21

thanks~
