### ISSUE TITLE
The svg file with transparent background didn't act well inside a pink rect

### ISSUE THREAD

**Issue by meloalright** [Brooooooklyn/canvas#428]
This File [resize-svg.svg](https://github.com/Brooooooklyn/canvas/blob/main/example/resize-svg.svg) with transparent background

Case inside a pink rect:

```js
const { promises } = require('fs')
const { join } = require('path')

const { createCanvas, Image } = require('../index')

async function main() {
  const file = await promises.readFile(join(__dirname, './resize-svg.svg'))

  const image = new Image()
  image.src = file

  const w = 1000
  const h = 1000

  // resize SVG
  image.width = w / 2
  image.height = h / 2

  // create a canvas of the same size as the image
  const canvas = createCanvas(w, h)
  const ctx = canvas.getContext('2d')

  // fill the canvas with the image
  ctx.fillStyle = 'pink'
  ctx.fillRect(0, 0, w, h)
  ctx.drawImage(image, 250, 250)

  const output = await canvas.encode('png')
  await promises.writeFile(join(__dirname, 'transparent-background-svg.png'), output)
}

main()
```

Result in `@napi-rs/canvas`:

<img width="200" height="200" src="https://user-images.githubusercontent.com/11075892/154792261-4f78e7cb-4c15-4e8f-9d65-1fedab74c956.png">

Result in `HTML canvas` or `node-canvas`:

<img width="200" height="200" src="https://user-images.githubusercontent.com/11075892/154792303-fc65d62b-9bbd-4d1e-aba9-0665f1cf1f37.png">

**Comment by enzoferey** [comment]
I can confirm this is also happening to me. The pink rect doesn't have any effect on it, it's all SVGs that have no background are given a white one.
