### ISSUE TITLE
How can i get raw-buffer?

### ISSUE THREAD

**Issue by undermuz** [Brooooooklyn/canvas#429]
![image](https://user-images.githubusercontent.com/6875507/154823576-89a2b797-7464-4ac5-b468-1e921f108a18.png)
i have to put render to framebuffer

in node-canvas i do it by `canvas.toBuffer("raw")`

How can i get raw-buffer by `@napi-rs/canvas`?

**Comment by Brooooooklyn** [comment]
use `canvas.data()` API
