### ISSUE TITLE
Text isn't being drawn on Ubuntu

### ISSUE THREAD

**Issue by KhafraDev** [Brooooooklyn/canvas#430]
On Ubuntu, `fillText` does not seem to do anything.

```ts
import { createCanvas, GlobalFonts } from '@napi-rs/canvas';
import { writeFileSync } from 'fs';

const canvas = createCanvas(128, 128);
const ctx = canvas.getContext('2d');

GlobalFonts.registerFromPath('./Arial.ttf', 'Arial');

ctx.fillStyle = '#FF0000';
ctx.font = '16px Arial';

ctx.fillText('Hello!', 50, 50);
writeFileSync('./test.png', canvas.toBuffer('image/png'));
```

Windows:
![test](https://user-images.githubusercontent.com/42794878/156284622-151fc7b8-2261-419e-87ef-d0d7c1ac3362.png)

ubuntu:
![test](https://user-images.githubusercontent.com/42794878/156284567-5a60b592-8405-441f-a172-2737dc3deda6.png)

**Comment by KhafraDev** [comment]
If anyone wants to test, [here](https://github.com/matomo-org/travis-scripts/blob/master/fonts/Arial.ttf) is the font I use for ubuntu.

**Comment by apresmoi** [comment]
Hi @KhafraDev did you manage to solve this ? I'm facing the same issue

**Comment by KhafraDev** [comment]
The server I was using didn't pre-install any fonts, so nothing could be written. You could manually register the fonts, or install packages that come with fonts.
