### ISSUE TITLE
measureText doesn't include spaces at the end

### ISSUE THREAD

**Issue by n3oney** [Brooooooklyn/canvas#441]
If you pass a space at the end of measureText, it won't include it in the measurements. This isn't the case for when the space is at the beginning.
Additionally, passing just a space gives a width of 0.
```js
const {createCanvas} = require('@napi-rs/canvas');

const canvas =  createCanvas(1080, 600);
const ctx = canvas.getContext('2d');

const texts = [
  'hello ',
  ' hello',
  'hello',
  ' '
];

for(const text of texts) {
  console.log(ctx.measureText(text).width)
}
```

Output:
```sh
25
30
25
0
```

The same inputs (with a different font obviously) produce this in Brave:
```sh
23.90625
23.90625
21.1279296875
2.7783203125
```

**Comment by meloalright** [comment]
看起来 `skiac_canvas_get_line_metrics_or_draw_text` 的返回结果确实就是这样的
