### ISSUE TITLE
 Can `CanvasRenderingContext2D.drawImage()` support `HTMLCanvasElement` as image parameter ?

### ISSUE THREAD

**Issue by erha19** [Brooooooklyn/canvas#444]
I am trying to use `@napi-rs/canvas` to replace the `canvas` dependence on our project,  see https://github.com/opensumi/core/pull/445

Thanks for your work in #424, it almost works but there have some new problems:

The `xterm.js` use a `HTMLCanvasElement` as the image parameter in `CanvasRenderingContext2D.drawImage()` on first load , see:

- [DynamicCharAtlas.ts#L202](https://github.com/xtermjs/xterm.js/blob/master/src/browser/renderer/atlas/DynamicCharAtlas.ts#L202)
- [CanvasRenderingContext2D/drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage)

But the `drawImage` API in `@napi-rs/canvas` just supports the `Image` type, I found the latest PR on #135.

@Brooooooklyn Can you support `HTMLCanvasElement` parameter ?  Thanks!

**Comment by mjgerace** [comment]
This would be a great change!

**Comment by mikrosystheme** [comment]
Maybe I am not understanding the issue, but [drawImage](https://github.com/Brooooooklyn/canvas/blob/main/index.d.ts#L256-L268) already supports canvas sources.

**Comment by Brooooooklyn** [comment]
Yes, it was supported
