### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by mattiaz9** [Brooooooklyn/canvas#487]
Hi, I'm getting the following error:
```
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

Do I need to do something else to make it work with NextJS?

**Comment by mattiaz9** [comment]
No, I'm using it in getStaticProps

**Comment by mattiaz9** [comment]
@Brooooooklyn thank you. Good to know for the future.
I needed canvas to generate a base64 image from blurhash, and I ended up creating my own decoder: https://gist.github.com/mattiaz9/53cb67040fa135cb395b1d015a200aff

So I don't need canvas anymore.

**Comment by christianledgard** [comment]
If someone is still experiencing this on NextJs, you can set the package in the following way:
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['@napi-rs/canvas'],
  },
}
 
module.exports = nextConfig
```
[Source: NextJs docs](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages)
