### ISSUE TITLE
ctx.filltext(): when drawing text with spaces, it seems that only the first word complies with ctx.textAlign

### ISSUE THREAD

**Issue by ppbl** [Brooooooklyn/canvas#488]
```js
ctx.textAlign = 'center'
ctx.fillText('兔 宝 宝'， 100)
```

Like this, on the browser, the '兔 宝 宝' will be centered as a whole, but using @n-api/canvas, it seems that the '兔' is centered alone, and the remaining words are arranged behind the ’兔‘

![image](https://user-images.githubusercontent.com/33046279/176110794-46d0baf9-284b-483c-aa55-632188e1d33d.png)

**Comment by Brooooooklyn** [comment]
I couldn't reproduce with the latest version:

```
  ctx.font = '48px Sarasa Fixed J'
  ctx.textBaseline = 'bottom'
  ctx.fillText('蒙娜丽莎', 50, 50)
  ctx.fillText('兔 宝 宝', 50, 200)
```
![text-align-with-space](https://user-images.githubusercontent.com/3468483/176455572-1cac9fee-a26c-4888-b8c5-c344faba6871.png)

**Comment by ppbl** [comment]
> ```js
> ctx.textAlign = 'center'
> ```

The point is ctx.textAlign = 'center'

**Comment by Brooooooklyn** [comment]
If you are using some rendering framework like echarts, it may cause by https://github.com/Brooooooklyn/canvas/issues/476

**Comment by Brooooooklyn** [comment]
It may relate to the font family, what font family do you use in this case?

**Comment by ppbl** [comment]
It should be related to font family. I tried PingFang SC and it was right. Maybe there is no Sarasa Fixed J on my computer
