### ISSUE TITLE
v0.1.24/0.1.25 breaks Vercel deployment

### ISSUE THREAD

**Issue by controversial** [Brooooooklyn/canvas#501]
If I deploy my project to Vercel with `"@napi-rs/canvas": "0.1.23",` in my package.json, everything goes smoothly. If I update to 0.1.25, everything works locally (my development environment is `darwin-arm64`) but when I deploy to production on Vercel, it creates a runtime error: `Error: Cannot find module '@napi-rs/canvas-linux-x64-gnu'`

Possibly related is that when I install `@napi-rs/canvas@0.1.23`, my package-lock.json fills with "resolved" URLs and checksums for the compiled packages for all of the different platforms, whereas when I install `@napi-rs/canvas@0.1.25`, my package-lock.json only has a "resolved" URL and checksum for darwin-arm64:

<img width="1663" alt="Screen Shot 2022-07-08 at 5 43 43 PM" src="https://user-images.githubusercontent.com/10377391/178074233-f81e5e63-a79b-4b0c-9c43-62d57282acb7.png">

**Comment by Brooooooklyn** [comment]
@controversial It looks like an npm bug, what version of npm client did you use? 
Could you try to upgrade your npm version and regenerate the `package-lock.json` file again and make sure all the `optionalDependencies` are listed in the `package-lock.json` correctly?

**Comment by controversial** [comment]
Fixed after upgrading from npm@8.3.1 to npm@8.13.2. Strange! Thanks for your help :)
