### ISSUE TITLE
Shadow colour is the fillStyle instead of shadowColor

### ISSUE THREAD

**Issue by Mushroomcraft1** [Brooooooklyn/canvas#506]
What it should look like:
![image](https://cdn.discordapp.com/attachments/973632481788035132/999982815695343656/unknown.png)
What it looks like (ignore the font difference):
![image](https://cdn.discordapp.com/attachments/973632481788035132/999982773622296596/unknown.png)

The shadow colour is supposed to be black but instead it takes the colour of the fillStyle.

**Comment by Brooooooklyn** [comment]
@Mushroomcraft1 could you provide minimal reproducable scripts?

**Comment by Mushroomcraft1** [comment]
Seems to be only if the fillStyle is a gradient
```js
const canvas = require("@napi-rs/canvas").createCanvas(500, 500)
const ctx = canvas.getContext("2d")
const gradient = ctx.createLinearGradient(0, 0, 500, 500)
const colours = ["#FF0000", "#FF8800", "#FFFF00", "#88FF00", "#00FF00", "#00FF88", "#00FFFF", "#0088FF", "#0000FF", "#8800FF", "#FF00FF"]
for (let i in colours) gradient.addColorStop(i / (colours.length + 1), colours[i])
ctx.fillStyle = gradient
ctx.shadowColor = "#000000"
ctx.shadowBlur = 20
ctx.fillRect(50, 50, 400, 400) //shadowColour should be black but instead it is the gradient
require("fs").writeFileSync("./image.png", canvas.toBuffer())
```
![image](https://user-images.githubusercontent.com/58344772/180641071-1f58581e-722c-412b-ad33-276b9206e9c4.png)

**Comment by Mushroomcraft1** [comment]
@Brooooooklyn hey, sorry to disturb but did you forget?

**Comment by Brooooooklyn** [comment]
@Mushroomcraft1 sorry, I'm busy recently
