### ISSUE TITLE
[Error]: Can't install & run project (canvas-linux-arm64-gnu error)

### ISSUE THREAD

**Issue by LWJerri** [Brooooooklyn/canvas#507]
![image](https://user-images.githubusercontent.com/50290430/180600423-a8d30d85-e727-424e-afc8-a445b5bb7342.png)

**Comment by LWJerri** [comment]
![image](https://user-images.githubusercontent.com/50290430/180602034-41b75a42-722f-4cdd-8815-45c43715adc9.png)

**Comment by LWJerri** [comment]
Any information?

**Comment by Brooooooklyn** [comment]
You can upgrade the libstdc++ on your system, or wait for my fix in the next week

**Comment by LWJerri** [comment]
> You can upgrade the libstdc++ on your system, or wait for my fix in the next week

Hello. Any news?
