### ISSUE TITLE
Fonts fallback support

### ISSUE THREAD

**Issue by Waxaranai** [Brooooooklyn/canvas#511]
i've noticed something really annoying when using custom font that don't support some unicode, is there are any method to fallback it to other font that have unicode support?

**Comment by Brooooooklyn** [comment]
Actually, you can set multiple fonts via `ctx.font`: 

```js
ctx.font = '50px "Iosevka Slab, Apple Color Emoji"'
```
![text](https://user-images.githubusercontent.com/3468483/184536079-c8cab611-7a59-4811-b00a-0447fc800406.png)

**Comment by Waxaranai** [comment]
> 

Ahh, that's make my life easier. thanks
