### ISSUE TITLE
Segfault when trying to interact with empty strings

### ISSUE THREAD

**Issue by ImUrX** [Brooooooklyn/canvas#526]
I currently don't have time for debugging, but I wanted to at least report this.
I wanted to change from ``canvas`` to this one and I'm getting segfaults on windows and linux (both amd64). [Relevant code](https://github.com/ImUrX/sweetiebot/blob/2ad90a6d699e6f356d4f71808f961b8793d6f20e/src/commands/Weeb/japanese.ts#L86)

**Comment by Brooooooklyn** [comment]
@ImUrX could you provide a minimal reproduction step? like input dataset and codes.

**Comment by ImUrX** [comment]
oh yeah sorry
```js
const first = {
    word: "何故",
    reading: "なぜ",
    furigana: [""]
};
const word: JishoWord = {
    slug: "何故",
    is_common: true,
    tags: [],
    jlpt: [],
    japanese: [first],
    senses: [],
    attribution: {
        "jmdict": true,
        "jmnedict": false,
        "dbpedia": false
    },
    audio: {}
};
JapaneseCommand.generateFurigana(word);
```
after taking my time now, it seems its because of empty text in the ``first.furigana`` array
