### ISSUE TITLE
text not appear

### ISSUE THREAD

**Issue by KayrozDbs** [Brooooooklyn/canvas#534]
![image](https://user-images.githubusercontent.com/40074505/184975005-a33c948c-f56d-4325-b480-da9827829fc9.png)

i add my bot on my vps linux unbuntu 22.04 and when i start the canvas i have this for my membercount and other number .

**Comment by KayrozDbs** [comment]
u think it's because im on linux ? in local with windows it's worked

**Comment by Brooooooklyn** [comment]
Have you called `GlobalFonts.register` before rendering?

**Comment by KayrozDbs** [comment]
On local i dont get that and its worked , on linux u need that ?

**Comment by KayrozDbs** [comment]
i write this : const { registerFont } = require('canvas');
        registerFont('./fonts/CercoDEMO-Black.otf', { family: 'Cerco DEMO Black' })

**Comment by KayrozDbs** [comment]
i need dependency for linux 22.04 unbuntu ?

**Comment by Brooooooklyn** [comment]
@KayrozDbs What are the missing characters in your example? Does the `Cerco DEMO Black'` contains the missing characters? You may register another font that contains these characters and set it as the fallback font.

>  const { registerFont } = require('canvas');

Seems like you are not using this library, this library is `@napi-rs/canvas`, not `'canvas'`

**Comment by KayrozDbs** [comment]
yes i change by only canvas and it's work and if i need register this font
in canvas what i need ?

**Comment by Brooooooklyn** [comment]
https://github.com/Brooooooklyn/canvas/blob/main/index.d.ts#L353
