### ISSUE TITLE
js-binder throws a loadError (canvas-linux-arm-gnueabihf)

### ISSUE THREAD

**Issue by kkakdugee** [Brooooooklyn/canvas#535]
I am currently trying to host a Discord bot that utilizes Canvas on my Raspberry Pi 4 Model B, but I am receiving a similar error to closed issue #507. Is there a way to fix this? 

![2022-08-08-001233_1847x337_scrot](https://user-images.githubusercontent.com/75061722/184837304-75b5d2e8-2374-4faa-ace1-8f7bac59be6a.png)
 
My libstdc++6 is up to date, but the issue still remains. ([your suggested solution](https://github.com/Brooooooklyn/canvas/issues/507#issuecomment-1193167321))

**Comment by Brooooooklyn** [comment]
@kkakdugee this library only static linked `libc++` on `x86_64-linux-gnu` and `aarch64-linux-gnu`. For `arm-linux-gnueabihf` you will need a newer `libstdc++` installed, and `libstdc++6` is too old, you will need to upgrade it.

**Comment by kkakdugee** [comment]
That worked, thank you.
