### ISSUE TITLE
Error: Cannot find module '@napi-rs/canvas-win32-ia32-msvc'

### ISSUE THREAD

**Issue by Abadima** [Brooooooklyn/canvas#550]
Um, what?

**Comment by Brooooooklyn** [comment]
This package doesn't support windows x32 system

**Comment by Abadima** [comment]
But it works just fine before, despite no upgrades? All I did was reset my pc (x64)

**Comment by Brooooooklyn** [comment]
@Abadima I guess you installed `x32` Node.js

**Comment by Abadima** [comment]
That's odd, since it works just fine on another project using the same version, the issue happens when I try to install & use it without another package

**Comment by Abadima** [comment]
..I fixed it by switching to `x64` version of NodeJS & reinstalling the package afterwards
Sincere apologies, have a great day and thanks for your help.
