### ISSUE TITLE
Canvas.loadImage

### ISSUE THREAD

**Issue by NotDemonix** [Brooooooklyn/canvas#554]
I tried using `loadImage` but i get:
`thread '<unnamed>' panicked at 'range end index 10 out of range for slice of length 0', library\core\src\slice\index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
any ideas?

**Comment by mjgerace** [comment]
Hello friend - I am not the project maintainer but you could probably help by giving more context. A good starting point would be indicating what kind of resource you are loading from - as [you can see](https://github.com/Brooooooklyn/canvas/blob/3377ca58b04691648626456ed92bba7cae1f4de4/load-image.js#L13), loadImage takes in many different sources - a URL, string, image, or buffer. Provide what source you are trying to load from and we might have an easier time reproducing the issue.

**Comment by NotDemonix** [comment]
> Hello friend - I am not the project maintainer but you could probably help by giving more context. A good starting point would be indicating what kind of resource you are loading from - as [you can see](https://github.com/Brooooooklyn/canvas/blob/3377ca58b04691648626456ed92bba7cae1f4de4/load-image.js#L13), loadImage takes in many different sources - a URL, string, image, or buffer. Provide what source you are trying to load from and we might have an easier time reproducing the issue.

I think i fixed it somehow but i was using local file, for remote files i get them to buffer from undici

**Comment by NotDemonix** [comment]
nvm, still broken, it only happens on one image, other work

**Comment by NotDemonix** [comment]
wait, does loadImage take path from package.json folder? (like fs)

**Comment by NotDemonix** [comment]
ok nvm it doesnt, so i do it correctly

**Comment by NotDemonix** [comment]
if i have for example `./././././data/images/image.jpg` it doesnt work but when i have `./././././data/images/folder/image.jpg` it does

**Comment by NotDemonix** [comment]
ok nvm it doesnt, but for images it does
can it be somehow cuz napi-rs doesnt have access to images?

**Comment by mjgerace** [comment]
@NotDemonix I load images just fine with napi-rs from local disk. I don't mean to be annoying/rude, but if you give example code or an example repo, we could probably help much better! Simply upload a bare-minimum example of you trying to load a file to github, with the file, so we can pull it and see if we can reproduce.

**Comment by Voroniyx** [comment]
Hey, I have the same problem, I give the function only buffers, I solved it temporarily with RUST_BACKTRACE=1, but I think this is not a permanent solution, here are some examples:
```ts
//1)
//baseBackground has the type string
const canvas = createCanvas(1232, 672);
const ctx = canvas.getContext('2d')
const cardBackground = await loadImage(Buffer.from(baseBackground, 'base64'));
ctx.drawImage(cardBackground, 0, 0)

2)
//generateBaseSalmonRunRotation has the type Buffer
const canvas = createCanvas(1232, 672);
const ctx = canvas.getContext('2d')
const base = await loadImage(await generateBaseSalmonRunRotation(data as SalmonRunRotation, monthlyGear))
ctx.drawImage(base, 0, 0)
```

**Comment by NotDemonix** [comment]
I actually fixed it..
Idk how but it does work for a while now.
