### ISSUE TITLE
Regression with globalAlpha in 0.1.29

### ISSUE THREAD

**Issue by KhafraDev** [Brooooooklyn/canvas#558]
After updating to @napi-rs/canvas@1.2.9 I noticed my app having problems. After downgrading, everything started to work again. Sorry for the not-really-minimal repro but it was the best I could do. I think globalAlpha is the issue here, but I'm not really sure.

Basically I just create a gif with 6 frames, where every other frame is alternating, and 1 frame has a lower alpha than the other.

000.png
![000](https://user-images.githubusercontent.com/42794878/189776969-faebc6c0-46d4-484e-b2a8-a92d3849d6ea.png)

FFF.png
![FFF](https://user-images.githubusercontent.com/42794878/189776983-91ccfd27-41e3-41a7-afa4-ae17a75b87c8.png)

test.js
```js
import { createCanvas, Image } from '@napi-rs/canvas'
import { GifEncoder } from '@skyra/gifenc'
import { readFileSync, writeFileSync } from 'fs'
import { buffer } from 'stream/consumers'

const encoder = new GifEncoder(256, 256)
	.setRepeat(0)
	.setDelay(20)
	.setQuality(100)

const imageHex = [
	'FFF',
	'000'
]

const stream = encoder.createReadStream()
encoder.start()

const canvas = createCanvas(256, 256)
const ctx = canvas.getContext('2d')

for (const hex of imageHex) {
	const image = new Image()
	image.height = image.width = 256
	image.src = readFileSync(`./${hex}.png`)
	
	const image2 = new Image()
	image2.height = image2.width = 256
	image2.src = readFileSync(`./${hex === 'FFF' ? '000' : hex}.png`)

	ctx.globalAlpha = 1
	ctx.drawImage(image, 0, 0)

	ctx.globalAlpha = 0.5
	ctx.drawImage(image2, 0, 0)

	const bytes = ctx.getImageData(0, 0, 256, 256).data
    encoder.addFrame(bytes)
}

encoder.finish()

writeFileSync('./test-0.1.28.gif', await buffer(stream))
```

Output v1.1.29
![test](https://user-images.githubusercontent.com/42794878/189777098-b94e6886-c475-4c28-90d9-5efaf512074c.gif)

Output v1.1.28
<details>
  <summary>Flashing image warning</summary>

![test-0 1 28](https://user-images.githubusercontent.com/42794878/189777176-53de340f-caf8-4030-b143-8760cd5ce1f8.gif)
  
</details>

**Comment by Brooooooklyn** [comment]
@KhafraDev this is a bug in previous version see https://github.com/Brooooooklyn/canvas/issues/539, the `globalAlpha` should not apply to images

**Comment by KhafraDev** [comment]
node canvas behaves similarly to v0.1.28, this is likely an unexpected change for a few people. According to the [spec](https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-global-alpha) as well: `[t]he global alpha value gives an alpha value that is applied to shapes and images before they are composited...`.

I believe globalAlpha also affects images on the browser, at least, according to some [stackoverflow](https://stackoverflow.com/a/18949160/15299271) [posts](https://stackoverflow.com/a/31708778/15299271).
