### ISSUE TITLE
<Context>.measureText() returns 0's for everything on Linux build

### ISSUE THREAD

**Issue by Mushroomcraft1** [Brooooooklyn/canvas#559]
I am using the `linux-x64-gnu` build and when I try to measure text, I get all 0's.

Code to reproduce:
```js
const Canvas = require("@napi-rs/canvas")
const canvas = Canvas.createCanvas(400, 400)
const ctx = canvas.getContext("2d")

ctx.font = "20px Calibri"
console.log(ctx.measureText("Test"))

/*
    Output:
    {
        actualBoundingBoxAscent: 0,
        actualBoundingBoxDescent: 0,
        actualBoundingBoxLeft: 0,
        actualBoundingBoxRight: 0,
        fontBoundingBoxAscent: 0,
        fontBoundingBoxDescent: 0,
        width: 0
    }
*/
```

**Comment by Brooooooklyn** [comment]
@Mushroomcraft1 have you registered font `Calibri`?

**Comment by Mushroomcraft1** [comment]
@Brooooooklyn isn't Calibri a default font? On windows I get the output ```js
/*
    {
        actualBoundingBoxAscent: 13,
        actualBoundingBoxDescent: 0,
        actualBoundingBoxLeft: 0,
        actualBoundingBoxRight: 32.517578125,
        fontBoundingBoxAscent: 15,
        fontBoundingBoxDescent: 5,
        width: 32.220001220703125
    }
*/
```

**Comment by Brooooooklyn** [comment]
Were there any system fonts on your Linux system?

**Comment by Mushroomcraft1** [comment]
Yes, I had fonts installed

![image](https://user-images.githubusercontent.com/58344772/189956651-5233a528-2b51-493e-a111-c1c48f742440.png)

**Comment by Mushroomcraft1** [comment]
Sorry for wasting your time, as it turns out the directories were wrong because I forgot that Linux uses a different directory system 😩. Again, thanks for the help and I'm so sorry.
