### ISSUE TITLE
The maxWidth parameter in fillText - text overflows

### ISSUE THREAD

**Issue by Spacey4K** [Brooooooklyn/canvas#577]
`maxWidth`: The maximum number of pixels wide the text may be once rendered.

```js
const pad = 10; // padding
ctx.textBaseline = 'top';
ctx.font = '16px Arial';

ctx.fillRect(0, 0, canvas.width, canvas.height);

ctx.fillStyle = 'blue';
ctx.fillRect(pad, pad, canvas.width - pad * 2, canvas.height - pad * 2);

const maxWidth = canvas.width - pad * 2;
ctx.fillStyle = 'white';
ctx.fillText('Short text', pad, 10, maxWidth);
ctx.fillText(`Very ${'long '.repeat(8)} text`, pad, 30, maxWidth);
```

This is how it is supposed to be rendered (chrome latest version)
![Browser:Expected](https://user-images.githubusercontent.com/68819139/198909075-efbd4454-c2af-485f-b4ac-9071ef634239.png)

Here is how this package rendered it. (text overflows out of the blue rectangle)
![Text leaks](https://user-images.githubusercontent.com/68819139/198909118-d89d9bcc-d52a-4979-8c05-3e07e7e08d9d.png)

Both rendered with the code above on a 200x60 canvas.

**Comment by Tancred423** [comment]
Also, the longer the text, the worse it gets:

![simple](https://user-images.githubusercontent.com/38757664/202287894-b5292475-728f-4723-8813-9a85f06ce41f.png)

<details>
  <summary>Code used (almost the same as Spacey's, but more repetitions)</summary>

  ```js
const { promises } = require('fs')
const { join } = require('path')
const { createCanvas } = require('@napi-rs/canvas')

const canvas = createCanvas(500, 100)
const ctx = canvas.getContext('2d')

const padding = 50
ctx.textBaseline = 'top'
ctx.font = '16px Arial'

ctx.fillRect(0, 0, canvas.width, canvas.height)

ctx.fillStyle = 'blue'
ctx.fillRect(padding, 0, canvas.width - padding * 2, canvas.height)

const maxWidth = canvas.width - padding * 2
ctx.fillStyle = 'white'
ctx.fillText('Short text', padding, 10, maxWidth)
ctx.fillText(`Very ${'long '.repeat(75)} text`, padding, 30, maxWidth)

async function main() {
    const pngData = await canvas.encode('png')
    await promises.writeFile(join(__dirname, 'simple.png'), pngData)
}

main()
  ```
</details>
