### ISSUE TITLE
CanvasRenderingContext2D.canvas is undefined

### ISSUE THREAD

**Issue by deyihu** [Brooooooklyn/canvas#588]
```js
const { createCanvas } = require('@napi-rs/canvas');
const canvas = createCanvas(1, 1);
const ctx = canvas.getContext('2d');
console.log(ctx.canvas);
//out:undefined
```

![Q%18(57}U8PG$E2I@D `I`R](https://user-images.githubusercontent.com/25998927/204727267-812205d6-86d5-4214-b1b0-5e9a05dab54b.png)

**Comment by mjgerace** [comment]
@Brooooooklyn this issue has surfaced for me too since 0.1.30 and breaks many existing applications.
