### ISSUE TITLE
Display unicode characters

### ISSUE THREAD

**Issue by Nicolas-Gth** [Brooooooklyn/canvas#591]
How can I display unicode characters ? 
A `↗` is supposed to be displayed here
![image](https://user-images.githubusercontent.com/78755503/207506678-6d203a4e-f402-4a8b-b6f4-e412ccd46ff3.png)

**Comment by Brooooooklyn** [comment]
@ThurstyWonk you should use `GlobalFonts.register` first to register fonts that contain emoji first, see https://github.com/Brooooooklyn/canvas/blob/main/__test__/draw.spec.ts#L884 for example

**Comment by ThurstyWonk** [comment]
I don't know why it shows as an emoji on github, but on windows it's a unicode like this :
![image](https://user-images.githubusercontent.com/78755503/207515046-f4262253-9024-4545-9e74-7f6c4fde2ed9.png)
So I've installed the apple emoji font but isn't there a way to replace automatically  the characters that my other font can't handle like windows is doing when I'm running my code on vs code ?
