### ISSUE TITLE
Example usage with fabric.js or Konva.

### ISSUE THREAD

**Issue by seanghay** [Brooooooklyn/canvas#593]
Both libs depend on `node-canvas` how can we use `@napi-rs/canvas` as a replacement for `node-canvas`?

**Comment by seanghay** [comment]
I think this should be in discussions tab 😐

**Comment by AngeloCore** [comment]
I think you should ask them, not here

**Comment by Brooooooklyn** [comment]
I need to pass the integration tests in `fabric` / `Konva` first, I don't have time to do this right now

**Comment by seanghay** [comment]
Is it possible to make `@napi-rs/canvas` to have the same API as `node-canvas`? If that possible I would like to create an adapter just for that and then alias that in `package.json`.

**Comment by ajoslin103** [comment]
I'm trying to swap in `@n-api/canvas` with webpack

`new NormalModuleReplacementPlugin(/(?<!@n-api.)canvas/, "@napi-rs/canvas"),`

But am not best with regex and so it's recursing and giving this error

ERROR in ./node_modules/@napi-rs/canvas/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/fm4/node_modules/@napi-rs/canvas/@napi-rs/canvas'

-- I like @seanghay 's idea to match the API !!
