### ISSUE TITLE
Unhandled error on `ctx.arc()`

### ISSUE THREAD

**Issue by okwme** [Brooooooklyn/canvas#645]
Hello,
thanks for the repo, really hoping to replace dependency hell of https://github.com/Automattic/node-canvas with this. However when simply swapping it I got an unhandled error.

The error is:
```
Error - Failed to convert napi value into rust type `bool`
```

The line of code it fails on is:
```js
        ctx.arc(x - (radius), y, radius * 2, rotate, rotate + .4 * Math.PI, 0);
```

I'm drawing some circles on a canvas, more context follows:
```js
  var size = 768
  var gridSize = 8
  var margin = 2
  const cnv = createCanvas(size, size)
  const ctx = cnv.getContext('2d')
  cnv.width = size
  cnv.height = size
  circleSize = size / (gridSize + margin * 2)
  radius = circleSize / 1.25
  rotate = 0
  for (var i = 0; i < gridSize; i++) {
    for (var j = 0; j < gridSize; j++) {
      var x = (i * circleSize) + (circleSize / 2);
      var y = (j * circleSize) + (circleSize / 2);
      ctx.fillStyle = color
      ctx.beginPath();
      ctx.arc(x - (radius), y, radius * 2, rotate, rotate + .4 * Math.PI, 0);
    }
  }
```

Im using node `v18.11.0` and @napi-rs/canvas `v0.1.37` on a mac with v12.6.3 Monterey and an Intel processor

**Comment by okwme** [comment]
The error also happens with node `v16.19.1`

**Comment by Brooooooklyn** [comment]
@okwme it's because the last param of `arc` is supposed to be `Boolean`, but provided `0` here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc
I'll fix it by converting it into the `Boolean` value.

**Comment by okwme** [comment]
Ah thank you that seems to have fixed it!
