### ISSUE TITLE
Unhandled error on setting Image src (Failed to create reference from Buffer)

### ISSUE THREAD

**Issue by okwme** [Brooooooklyn/canvas#646]
Thanks for responding to #645 so quickly!  
I'm still having an error after switching to this library unfortunately.  
Now it's coming when i set the `src` of an Image.  
The error is:
```
Error - Failed to create reference from Buffer
```

The line that triggers it is:
```js
      drawing.src = src
```

And the code with more context follows:
```js
     const { Image, createCanvas } = require('@napi-rs/canvas')

      var drawing = new Image();
      var src = `http://someURL.com/imageThatLoads.png`
      drawing.onload = function () {
        ctx.drawImage(drawing, 0, 0, width, width);
      };
      drawing.src = src
```

**Comment by Brooooooklyn** [comment]
`const image = await loadImage('http://someURL.com/imageThatLoads.png')`

**Comment by okwme** [comment]
thank you!

**Comment by Conpeter** [comment]
> `const image = await loadImage('http://someURL.com/imageThatLoads.png')`

This only get 'Image {}'. Seems not working.
