### ISSUE TITLE
Feat: Add note in README about AWS Lambda layer

### ISSUE THREAD

**Issue by ShivamJoker** [Brooooooklyn/canvas#654]
Hello, Thanks for this great library.
I have planned to distribute Lambda layers for the `canvas` library.

Here is the repo which automatically generates the layer every week: https://github.com/ShivamJoker/Canvas-Lambda-Layer

I can send a PR if you are fine with it.

**Comment by nbusser** [comment]
It was super-useful as a workaround for my issue #660  
Thank you

**Comment by ShivamJoker** [comment]
> It was super-useful as a workaround for my issue #660 Thank you

Glad I could help.

**Comment by Brooooooklyn** [comment]
@ShivamJoker hey thanks! I'm sorry I didn't read your notification for this issue before, I've had too many GitHub notifications. Could you create a pull request for it? I'm happy to add it to the README
