### ISSUE TITLE
Is it possible to transpile the lib?

### ISSUE THREAD

**Issue by nbusser** [Brooooooklyn/canvas#660]
Hi,

I'm using a mac M1 and I want to build the lib for a linux system (AWS lambda).

When I install the package on my computer, I have the following file-tree:
![file tree](https://user-images.githubusercontent.com/25375465/233182826-0ae46266-2a66-4ae1-a762-e56fd985cee4.png)

When running the lambda on AWS, I have the following error message:
![logs](https://user-images.githubusercontent.com/25375465/233183095-24745087-30af-44ae-a375-3d1ae33f8522.png)

I conclude that npm build script builded a specific version for my architecture.  
**Is it then possible to transpile the lib for another architecture ?**

**Comment by nbusser** [comment]
As a workaround, I used [this lambda layer](https://github.com/ShivamJoker/Canvas-Lambda-Layer), which contains the lib properly compiled for AWS lambda execution environment.

**Comment by ShivamJoker** [comment]
@nbusser since it uses the binary which is compiled, you will have to use the layers or copy the node modules.
You need to ignore the lib while compiling.

**Comment by nbusser** [comment]
@ShivamJoker I added the lib in my builder's (esbuild) externals.  
I registered your layer in my serverless function and everything seems to work correctly!

**Comment by ShivamJoker** [comment]
That's great. I think you can close the issue now, since there is no other way to use it.

**Comment by nbusser** [comment]
Don't you think it is possible to somehow transpile the library to produce a linux build?

I'm thinking of using some shady npm arguments or stuff.

**Comment by ShivamJoker** [comment]
You can't compile a compiled binary.

Ideally npm packages contain mostly js and CSS which the transpiler understands.

At the end the library is just executing the binary when you call the API via js.

**Comment by nbusser** [comment]
Ok I now understand what you mean, makes sense!

However, there should be one different binary for each architecture.  
Then, is there a way to tell npm to install ("setup") the js lib to use the linux x86 binary?

**Comment by ShivamJoker** [comment]
I think there are some flags which you can use, but the best way to get it is by installing it in a system where you'll be running eg. Amazon linux 2.

**Comment by Brooooooklyn** [comment]
@nbusser see https://github.com/npm/rfcs/pull/519#issuecomment-1439977845

**Comment by juaoose** [comment]
Hijacking this since I defaulted to the layer. In "theory", something like `npm install --no-save --arch=x86 --platform=linux ...` would work if done from CI? Or am I not understanding?

Thanks for the lib :)
