### ISSUE TITLE
Remote source rejected with status code

### ISSUE THREAD

**Issue by acarslck** [Brooooooklyn/canvas#663]
"Remote source rejected with status code"
I encountered the error screenshot attached.
When a user joins the server, I create a custom image and post that image to the server channel. I'm letting you know as a last resort. I would be glad if you help.

![](https://i.ibb.co/3mD3brN/error.png)

**Comment by skdhg** [comment]
`remote source rejected with status code 404` indicates that the image url you provided to `loadImage` function does not exist.

You can find more info about `404 status code` here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

**Comment by designbyacar** [comment]
> `remote source rejected with status code 404` işlev için sağladığınız resim URL'sinin mevcut olmadığını gösterir.`loadImage`
> 
> Daha fazla bilgiyi burada bulabilirsiniz https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404`404 status code`

the location of the picture is correct no problem

**Comment by designbyacar** [comment]
> `remote source rejected with status code 404` indicates that the image url you provided to `loadImage` function does not exist.
> 
> You can find more info about `404 status code` here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

the location of the picture is correct no problem

**Comment by skdhg** [comment]
> > `remote source rejected with status code 404` indicates that the image url you provided to `loadImage` function does not exist.
> > You can find more info about `404 status code` here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
> 
> the location of the picture is correct no problem

Could you share the url here? Does the url require authorization credentials or some headers?

**Comment by designbyacar** [comment]
picture directly in folder
![image](https://user-images.githubusercontent.com/69026667/233637570-9600f8e4-115c-43ba-b58e-49efa3405ac5.png)

**Comment by designbyacar** [comment]
> > > `remote source rejected with status code 404` indicates that the image url you provided to `loadImage` function does not exist.
> > > You can find more info about `404 status code` here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
> > 
> > 
> > the location of the picture is correct no problem
> 
> URL'yi burada paylaşabilir misiniz? URL, yetkilendirme kimlik bilgileri veya bazı üstbilgiler gerektiriyor mu?

Picture directly in folder
![image](https://user-images.githubusercontent.com/69026667/233637689-27a85bac-00a1-4ba9-af15-ce96911aa6f1.png)

**Comment by designbyacar** [comment]
> > > `remote source rejected with status code 404` indicates that the image url you provided to `loadImage` function does not exist.
> > > You can find more info about `404 status code` here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
> > 
> > 
> > the location of the picture is correct no problem
> 
> Could you share the url here? Does the url require authorization credentials or some headers?

Picture directly in folder
![image](https://user-images.githubusercontent.com/69026667/233637789-4c090741-5ac8-4eac-9867-9bfdc1239005.png)

**Comment by designbyacar** [comment]
in the file directory like this
![image](https://user-images.githubusercontent.com/69026667/233637952-1a2adb77-db46-49e5-b71e-627f14c00c79.png)

**Comment by designbyacar** [comment]
in the file directory like this

![image](https://user-images.githubusercontent.com/69026667/233638095-c02d5d61-4006-4e31-bcad-ecfac75ee331.png)

**Comment by designbyacar** [comment]
when the user joins the server, I create a custom image and post that image to the server channel

**Comment by designbyacar** [comment]
```js
const { client } = require("../server")
const { AttachmentBuilder, Colors } = require("discord.js")
const { createCanvas, loadImage , GlobalFonts } = require('@napi-rs/canvas');
const { resolve } = require("path");
GlobalFonts.registerFromPath(resolve(process.cwd(), "font", "RobotoMono-Bold.ttf"), "RobotoMono-Bold");
GlobalFonts.registerFromPath(resolve(process.cwd(), "font", "Catrinity.otf"), "Catrinity");

client.on('guildMemberAdd', async (member) => {
    let channel = client.channels.cache.get("1091436089807491172")
    let status = member?.presence?.status
    if (!status) status = client.guilds.cache.get(member.guild.id).members.cache.get(member.user.id)?.presence?.status
    setTimeout(async () => {
        let datas = {
            "online": { img: "https://cdn.discordapp.com/attachments/834186187232903208/1009882589210890250/online.png", color: "#43b581", },
            "offline": { img: "https://cdn.discordapp.com/attachments/834186187232903208/1009882793821618276/invisible.png", color: "gray", },
            "dnd": { img: "https://cdn.discordapp.com/attachments/834186187232903208/1009883129307213864/dnd2.png", color: "red", },
            "idle": { img: "https://cdn.discordapp.com/attachments/834186187232903208/1031648495096057987/6868-idle.png", color: "orange", }

        }

        let statusImage = status ? datas[status].img : datas["offline"].img
        let statusColor = status ? datas[status].color : datas["offline"].color

        let canvas = createCanvas(500, 180)
        let ctx = canvas.getContext("2d");
        let background = await loadImage("./images/background.png");
        ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
        //ctx.strokeStyle = '#74037b';
        ctx.shadowColor = statusColor;
        ctx.shadowBlur = 1;
        ctx.strokeRect(0, 0, canvas.width, canvas.height);

        ctx.font = '18px Catrinity';
        ctx.fillStyle = statusColor;
        ctx.textAlign = 'center';
        ctx.fillText(`${member.displayName.length > 8 ? member.displayName.substring(0, 17) + '' : member.displayName}`, canvas.width / 5.0, canvas.height / 1.1);

        //Hashtag kısmı ayarı
        ctx.beginPath()
        ctx.font = '20px RobotoMono-Bold';
        ctx.fillStyle = statusColor;
        ctx.shadowColor = statusColor;
        ctx.shadowBlur = 1;
        ctx.fillText(`# Sunucuya Giriş Yaptı!`, canvas.width / 1.5, canvas.height / 2.2);
        ctx.stroke();
        ctx.restore()

        //Avatar ayarı
        const avatar = await loadImage(member.user.displayAvatarURL({ format: 'png' }));
        ctx.save();
        ctx.arc(100, 80, 60, 0, Math.PI * 2, true);
        ctx.clip();
        ctx.drawImage(avatar, 35, 15, 130, 130);
        ctx.restore()

        //Statü çerçeve
        const d = await loadImage(statusImage)
        ctx.beginPath()
        ctx.arc(100, 80, 60, 0, Math.PI * 2, true);
        ctx.shadowColor = statusColor;
        ctx.shadowBlur = 2;
        ctx.lineJoin = 'bevel';
        ctx.lineWidth = 3;
        ctx.strokeStyle = statusColor;
        //ctx.arc(380, 185, 120, 0, Math.PI * 2, true);
        ctx.stroke();
        ctx.restore()

        //Statü resmi
        ctx.beginPath()
        ctx.drawImage(d, 125, 110, 30, 30)
        ctx.lineWidth = 4;
        ctx.strokeStyle = '#000000';
        ctx.stroke();

        let attachment = new AttachmentBuilder(await canvas.encode('png'), { name: `hosgeldin-${member.user.id}.png` });

        let embed = {
            description: `${member.user.bot ? `${member} \`Bot\`` : `${member} \`Kullanıcı\``} - Sunucuya Giriş Yaptı. \n<#705081409911521341> kanalını okumayı unutma!`,
            color: Colors.Blue,
            image: {
                url: `attachment://hosgeldin-${member.user.id}.png`
            }
        }

        return await channel.send({ embeds: [embed], files: [attachment] }).catch(e => console.log(e))
    }, 200);
})

```

**Comment by skdhg** [comment]
The url specified inside `datas` object seems to be the cause. It's returning `404` status code.

**Comment by skdhg** [comment]
You need to change your url to a valid one. Since this issue has nothing to do with this library, so we cannot suggest what url to use.

**Comment by designbyacar** [comment]
OK thanks

**Comment by designbyacar** [comment]
I added the image as the url and got the same error again

**Comment by designbyacar** [comment]
I think the problem I'm having is related to the module. Because the problem was new, I was using the same code in a complex way before.

**Comment by designbyacar** [comment]
done from scratch
