### ISSUE TITLE
Error: Cannot find module '@napi-rs/canvas-win32-x64-msvc'

### ISSUE THREAD

**Issue by muralianand12345** [Brooooooklyn/canvas#669]
Version @napi-rs/canvas: 0.1.25

`Error: Cannot find module '@napi-rs/canvas-win32-x64-msvc'
Require stack:
- C:\Users\smura\Desktop\New Roleplay\node_modules\@napi-rs\canvas\js-binding.js
- C:\Users\smura\Desktop\New Roleplay\node_modules\@napi-rs\canvas\index.js
- C:\Users\smura\Desktop\New Roleplay\commands\slash\image.js
- C:\Users\smura\Desktop\New Roleplay\handlers\commands\commands.js
- C:\Users\smura\Desktop\New Roleplay\bot.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\smura\Desktop\New Roleplay\node_modules\@napi-rs\canvas\js-binding.js:36:29)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\smura\\Desktop\\New Roleplay\\node_modules\\@napi-rs\\canvas\\js-binding.js',
    'C:\\Users\\smura\\Desktop\\New Roleplay\\node_modules\\@napi-rs\\canvas\\index.js',
    'C:\\Users\\smura\\Desktop\\New Roleplay\\commands\\slash\\image.js',
    'C:\\Users\\smura\\Desktop\\New Roleplay\\handlers\\commands\\commands.js',
    'C:\\Users\\smura\\Desktop\\New Roleplay\\bot.js'
  ]
}`
Can someone help me out?

**Comment by Brooooooklyn** [comment]
does `@napi-rs/canvas-win32-x64-msvc` existed in your lock file?

**Comment by towner-10** [comment]
I am also getting a somewhat similar error as well.

```
"dependencies": {
    "@napi-rs/canvas": "^0.1.40",
    "@napi-rs/canvas-win32-x64-msvc": "^0.1.40",
    "@types/node": "20.1.3",
    "@types/react": "18.2.6",
    "@types/react-dom": "18.2.4",
    "autoprefixer": "10.4.14",
    "eslint": "8.40.0",
    "eslint-config-next": "13.4.1",
    "fast-average-color-node": "^2.6.0",
    "next": "13.4.1",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
}
```

and I am getting the following error code:

```
- error ./node_modules/@napi-rs/canvas-win32-x64-msvc/skia.win32-x64-msvc.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@napi-rs/canvas-win32-x64-msvc/skia.win32-x64-msvc.node
./node_modules/@napi-rs/canvas/js-binding.js
./node_modules/@napi-rs/canvas/index.js
./lib/generate-image.ts
./app/api/now-playing/image/route.ts
```

I have tried to debug it by adding some webpack options to the bundle but nothing has really worked.

**Comment by SteadEXE** [comment]
I have the same issue, unable to make CI/CD if @napi-rs/canvas is present. 
I dev on Windows so @napi-rs/canvas-win32-x64-msvc is in lock file but CI/CD runs in Docker, so it fails.
The docker container uses "npm ci" to install deps, which, relies on lockfile and @napi-rs/canvas-linux-x64-gnu is not present.

You cannot add those two packages in your dependencies or you end up with a "EBADPLATFORM" error.

**Comment by lopo12123** [comment]
I solved the problem after installing vc_redist on my computer (FYI)

see https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/Brooooooklyn/canvas/pull/775
