### ISSUE TITLE
Valid images exits process silently

### ISSUE THREAD

**Issue by imranbarbhuiya** [Brooooooklyn/canvas#672]
When I use `loadImage` to load https://cdn.w1st.xyz/cards/characters/7457d9ce-9916-451b-8bc1-94eb50e26e23.jpg image, my process exits silently without any error.  Not only this, but there are other images too that exits like this.
![image](https://github.com/Brooooooklyn/canvas/assets/74945038/fb9c4b75-837a-4a83-99aa-da311072bd79)

This image works with `canvas` package. Also I can't handle the error on nodejs side with try/catch. It exits the process directly.

**Comment by nieyuyao** [comment]
can i take this issue?

**Comment by Brooooooklyn** [comment]
@nieyuyao niesure thanks
