### ISSUE TITLE
when rgba alpha=0   Not the expected drawing result

### ISSUE THREAD

**Issue by deyihu** [Brooooooklyn/canvas#684]
```js

const { createCanvas } = require('@napi-rs/canvas');
const fs = require('fs');
const canvas = createCanvas(100, 100);
const ctx = canvas.getContext('2d');
ctx.fillRect(0, 0, canvas.width, canvas.height);
//Should be drawn in a transparent manner
ctx.fillStyle = 'rgba(255,255,255,0)';
ctx.fillRect(0, 0, 20, 20);
fs.writeFileSync('./image.png', canvas.toBuffer('image/png'));
```

The expected drawn result should be transparent rather than not drawn

![(R7Z 43{9CQ4B2}LZ) U9XF](https://github.com/Brooooooklyn/canvas/assets/25998927/b85daad0-9404-4669-8c48-31d5c9843b13)

**Comment by skdhg** [comment]
I don't think this is a bug. The default fill style seems to be black, I tested it on browser, node-canvas and @napi-rs/canvas and got the same result as you have stated in this issue.

However, changing the fillStyle of initial `fillRect` seems to work as expected. Here is my updated code:

```js
const { createCanvas } = require('@napi-rs/canvas');
const fs = require('fs');

const canvas = createCanvas(100, 100);
const ctx = canvas.getContext('2d');

ctx.fillStyle = 'blue';
ctx.fillRect(0, 0, canvas.width, canvas.height);
ctx.fillStyle = 'rgba(255,255,255,0)';
ctx.fillRect(0, 0, 20, 20);
fs.writeFileSync('./image.png', canvas.toBuffer('image/png'));
```

The result is:
![image](https://github.com/Brooooooklyn/canvas/assets/46562212/8b975a19-1639-4d6a-9638-5040e7f51259)

**Comment by deyihu** [comment]
@skdhg 
I tried it in the browser, and it's true，
I always thought it would be filled in a transparent way
