### ISSUE TITLE
Fail to render text when working with Echarts

### ISSUE THREAD

**Issue by DeepJoyPo** [Brooooooklyn/canvas#694]
I tried to use the example code in #394 and additionally write to a local file.
`fs.writeFileSync('bar.png', canvas.toBuffer('image/png'))`
But the .png file lost all text information.

![noText](https://github.com/Brooooooklyn/canvas/assets/22149876/5d46f245-1406-4122-8c41-f3cbe461e4ef)

**Comment by Brooooooklyn** [comment]
You need to register fonts first

**Comment by DeepJoyPo** [comment]
> You need to register fonts first

I am not using a custom font.  I need to 

> You need to register fonts first

I don't get it. I just want to use system fonts. Still I need to register them?
If so, how should I register them?

**Comment by DeepJoyPo** [comment]
ok. I figure it out now. The key is you need to specify `textStyle: { fontFamily: **}` when setting EChart options. And you should check if the font is supported in `GlobalFonts.families`. If not, do `GlobalFonts.registerFromPath(thePathToYourFontFile)`
