### ISSUE TITLE
`ctx.globalCompositeOperation` not working as expected

### ISSUE THREAD

**Issue by twlite** [Brooooooklyn/canvas#695]
# Version

- `"@napi-rs/canvas": "^0.1.41"`
- Node.js: v20.0.0
- OS: Windows 11

# How to reproduce?

Let us consider the following as an example for `@napi-rs/canvas`

```ts
import { createCanvas } from '@napi-rs/canvas';
import { writeFile } from 'fs/promises';

async function main() {
  const width = 500,
    height = 500;

  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = 'red';
  ctx.fillRect(0, 0, width, height);

  ctx.globalCompositeOperation = 'destination-in';
  ctx.beginPath();
  ctx.arc(width / 2, height / 2, width / 2, 0, Math.PI * 2);
  ctx.closePath();
  ctx.fill();

  const buffer = await canvas.encode('png');
  await writeFile(`${__dirname}/output.png`, buffer);
}

main();
```

and the following for web browser:

```html
<canvas id="canvas" width="500" height="500"></canvas>
```

```js
const width = 500, height = 500;
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

ctx.fillStyle = 'red';
ctx.fillRect(0, 0, width, height);

ctx.globalCompositeOperation = 'destination-in';
ctx.beginPath();
ctx.arc(width / 2, height / 2, width / 2, 0, Math.PI * 2);
ctx.closePath();
ctx.fill();
```

# Expectation

The output of the browser looks like this:

![image](https://github.com/Brooooooklyn/canvas/assets/46562212/080b7c17-20f9-48f7-93f2-0f64963af055)

# Result

The output of `@napi-rs/canvas` looks like this:

![image](https://github.com/Brooooooklyn/canvas/assets/46562212/6c1a8055-5ebb-47ea-abb0-42c8a14373b0)

**Comment by nieyuyao** [comment]
It seems to be the expected behavior for blending of geometries?  https://skia.org/docs/user/api/skblendmode_overview/

**Comment by Brooooooklyn** [comment]
> It seems to be the expected behavior for blending of geometries?

yes, but we need to align the behavior with the browser

**Comment by Brooooooklyn** [comment]
> Can we refer to it to fix the issue?

@nieyuyao yes sure
