### ISSUE TITLE
Ram leak?

### ISSUE THREAD

**Issue by NotDemonix** [Brooooooklyn/canvas#716]
Seems like if I don't use clearAllCache() then the memory goes up every time something is rendered.

**Comment by themrrobert** [comment]
Confirm this issue.

The issue does not exist in 0.1.38, but it does exist in 0.1.44

Basically there is a huge memory leak, after generating a few hundred images (and discarding them), the RSS usage went up to > 1.4 GB

Even after clearAllCache(), it only recovered around 400MB  (1.0 GB used)

In 0.1.38, the same test is always around 600 MB rss, never above 700 MB

In the picture, I am running:
`util.inspect(process.memoryUsage())`

`clearAllCache()`

`util.inspect(process.memoryUsage())`
![image](https://github.com/Brooooooklyn/canvas/assets/10122432/ea9d2f06-34f2-4ef8-a86c-a08022ca1ffa)


In the picture below, I am running 0.1.38, and while the RSS does spike to around 1GB while the pictures are generating and shortly after, within 15 seconds the RSS is back to ~600MB as you can see here:
![image](https://github.com/Brooooooklyn/canvas/assets/10122432/dd4e9a93-d4ab-4f2d-b17f-268fda28d642)

**Comment by 7te3ep** [comment]
Same here, even clearAllCache() doesnt work.

**Comment by 7te3ep** [comment]
> Confirm this issue.
> 
> The issue does not exist in 0.1.38, but it does exist in 0.1.44
> 
> Basically there is a huge memory leak, after generating a few hundred images (and discarding them), the RSS usage went up to > 1.4 GB
> 
> Even after clearAllCache(), it only recovered around 400MB (1.0 GB used)
> 
> In 0.1.38, the same test is always around 600 MB rss, never above 700 MB
> 
> In the picture below, I am running 0.1.44, and the following code in the 3 commands: `util.inspect(process.memoryUsage())`
> 
> `clearAllCache()`
> 
> `util.inspect(process.memoryUsage())` ![image](https://private-user-images.githubusercontent.com/10122432/269518361-ea9d2f06-34f2-4ef8-a86c-a08022ca1ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzI1MzUsIm5iZiI6MTcwNTc3MjIzNSwicGF0aCI6Ii8xMDEyMjQzMi8yNjk1MTgzNjEtZWE5ZDJmMDYtMzRmMi00ZWY4LWE4NmMtYTA4MDIyY2ExZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE3MzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MmFlMzQ5YjhhNzI5NDllMDU2YWE3OTA1MjhiNDc5MDcxNTM4YWQxMTU1NDYwYzVkMTc5YWE4NTZlOGYzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dAGynfqHBubLnb0wOh0t3pTBhdTN5AAnFOumAnto4WI)
> 
> In the picture below, I am running 0.1.38, and while the RSS does spike to around 1GB while the pictures are generating and shortly after, within 15 seconds the RSS is back to ~600MB as you can see here: ![image](https://private-user-images.githubusercontent.com/10122432/269519113-dd4e9a93-d4ab-4f2d-b17f-268fda28d642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzI1MzUsIm5iZiI6MTcwNTc3MjIzNSwicGF0aCI6Ii8xMDEyMjQzMi8yNjk1MTkxMTMtZGQ0ZTlhOTMtZDRhYi00ZjJkLWIxN2YtMjY4ZmRhMjhkNjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE3MzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzlmZTM2MGQ2NzMxOWI0NWVmNGFjNzY0NzVkM2JhMjA2NjkwNWI5YTkyYzRlNzA1MjBhNDVhZWMxMWMzZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vdkBDAtfg4Y_7WatJxMklhzpKAcovlhplnByuqD2XJI)
> 
> Test conditions:
> 
> Node v: 18.16.1 Windows 11 and Linux Debian 10.13 @napi-rs/canvas version 0.1.38 (ok) and 0.1.44 (bugged) I generated 200 images per test, size 488 x 331 via new Canvas() and getContext('2d'), with 56 individual png's loaded as Images via loadImage(), overlaid onto the parent image with Canvas.drawImage(), and a simple text header drawn via 2dcontext.drawText(), exported as pngs, and discarded. Repeated the test with all images drawn 'at the same time' via promiseArray.push()... await Promise.all(promiseArray); and also await'ing each image, with virtually identical results. The results shown above are from the promiseArray variant.

I have the issue in 1.1.38 to

**Comment by SteadEXE** [comment]
I confirm the issue, RAM never get released, with 0.1.44

**Comment by barthuijgen** [comment]
I tested on `0.1.45` and saw no sigificant memory leak when inspecting `process.memoryUsage()` but once my application was containerised I saw HUGE memory leaks in the `docker stats` memory usage graphs. 

I managed to narrow it down to calling `canvas.toBuffer()` or `canvas.encode()`, as soon as I left this line out, the memory leak stopped occuring, but I also had no output...

I'm talking about 60~80MB of memory increase per render of a 8MB PNG.
Consistently, per render, that much increase I was getting over 1GB usage while on `0.1.41` it never goes above 200MB and after being idle for a bit sits on 75MB

And yes I also tried `clearAllCache` it did nothing.

Since this package has bindings to a native binary, it makes sense nodejs does not detect the memory leak.

I have not seen others report this yet, so figured I would report my findings. Hope it gets fixed sometime, until then pinning version to `0.1.41` works for me.

**Comment by 7f8ddd** [comment]
https://github.com/Brooooooklyn/canvas/blob/f3a699bbb5a1fae69ebb8a02499ce6279624afe1/src/lib.rs#L259

Is the usage of noop here the cause?

**Comment by Brooooooklyn** [comment]
I'm looking into this issue, what kind of image do you generate with `@napi-rs/canvas`? I'm trying to create a minimal repro

**Comment by SteadEXE** [comment]
In my case, a canvas  of size 3000x925. 

Method or attribute utilised (maybe usefull for a reproduction code):
`fillStyle, fillRect, textAlign, setLineDash, strokeRect, save, restore, translate, font, textBaseline, beginPath, moveTo, lineTo, closePath, fill, stroke, lineWidth, strokeStyle`

Then I call `canvas.toBuffer('image/jpeg')` to get my image.
Apparently this lead to the memory leak, but I didn't tested myself.

I have 3 registered fonts.

**Comment by Brooooooklyn** [comment]
@SteadEXE thank you, I'll try

**Comment by Brooooooklyn** [comment]
Does anyone actually catch a real-world oom? I'm wondering if the RSS is allocated memory, not the actually used memory.

**Comment by SteadEXE** [comment]
In my case, the process eat all the available RAM on Windows, until system itself run out of memory. 
Even after an idle period, RAM never got released, node process had to crash or be restarted.

**Comment by SteadEXE** [comment]
After some test, I can confirm after generating 1000+ images on my side I reach 4.5GB+ RAM, while I never go over 300 MB in 0.1.37.

**Comment by 7f8ddd** [comment]
> Does anyone actually catch a real-world oom? I'm wondering if the RSS is allocated memory, not the actually used memory.

The issue is an actual memory leak, as Bun.gc(true) would clear eg. large arrays or other things.
```
import { createCanvas } from "@napi-rs/canvas";

async function test() {
  const canvas = createCanvas(600, 600);

  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // The memory leak is much worse when the quality is high. It only leaks when this is called.
  await canvas.encode("webp", 100);
}

for (let i = 0; i < 5000; i++) {
  await test();
}

setInterval(() => {
  Bun.gc(true);
  console.log(process.memoryUsage().rss / 1024 / 1024);
}, 1000);
```

**Comment by Brooooooklyn** [comment]
Can you try this version to see if it has fixed your issue? https://github.com/Brooooooklyn/canvas/releases/tag/v0.1.48 ?

**Comment by 7f8ddd** [comment]
> Can you try this version to see if it has fixed your issue? https://github.com/Brooooooklyn/canvas/releases/tag/v0.1.48 ?

For me, it seems like it's still leaking the same amount on 0.1.48.

**Comment by Brooooooklyn** [comment]
@7te3ep I can't reproduce the leak with the code:

```js
import { createCanvas } from './index.js'

async function test() {
  const canvas = createCanvas(2560, 1920)
  const ctx = canvas.getContext('2d')
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  await canvas.encode("webp", 100);
}

for (let i = 0; i < 50; i++) {
  await test();
  global?.gc?.()
  console.info(process.memoryUsage().rss / 1024 / 1024 + " MB");
}

setInterval(() => {
  console.info(process.memoryUsage().rss / 1024 / 1024 + " MB");
}, 1000);

```

On my MacBook, the output was like:

```
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
285.234375 MB
``` 

As you can see, the memory usage is very stable

**Comment by 7f8ddd** [comment]
> @7te3ep I can't reproduce the leak with the code:
> 
> ```js
> import { createCanvas } from './index.js'
> 
> async function test() {
>   const canvas = createCanvas(2560, 1920)
>   const ctx = canvas.getContext('2d')
>   ctx.fillStyle = "black";
>   ctx.fillRect(0, 0, canvas.width, canvas.height);
> 
>   await canvas.encode("webp", 100);
> }
> 
> for (let i = 0; i < 5000; i++) {
>   await test();
>   global?.gc?.()
>   console.info(process.memoryUsage().rss / 1024 / 1024 + " MB");
> }
> 
> setInterval(() => {
>   console.info(process.memoryUsage().rss / 1024 / 1024 + " MB");
> }, 1000);
> ```
> 
> On my MacBook, the output was like:
> 
> ```
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> 285.234375 MB
> ```
> 
> As you can see, the memory usage is very stable

I'm not sure if you were replying to me, but it's leaking with png, not webp. webp is fine now.

**Comment by Brooooooklyn** [comment]
Confirmed that PNG is still leaking, I will fix it immediately.

**Comment by SteadEXE** [comment]
For me it looks like the issue is fixed, thank you 🥇
