### ISSUE TITLE
⨯ ./node_modules/@napi-rs/canvas-linux-x64-gnu/skia.linux-x64-gnu.node

### ISSUE THREAD

**Issue by sahnoun99** [Brooooooklyn/canvas#727]
I just tried to use it in next js api routes then i got this error :  

⨯ ./node_modules/@napi-rs/canvas-linux-x64-gnu/skia.linux-x64-gnu.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

my machine is pop os (ubuntu based distro).

**Comment by Brooooooklyn** [comment]
You need https://webpack.js.org/loaders/node-loader/ for `.node` file
