### ISSUE TITLE
2000x slower drawImage 

### ISSUE THREAD

**Issue by gc** [Brooooooklyn/canvas#867]
drawImage appears to be 2000x slower than other canvas libraries.

The benchmark is drawing lots of parts of a big image (i.e sprites/spritesheets)

**NAPI Canvas** Average: 2413.62 ms, Min: 2338.18 ms, Max: 2525.64 ms
**Node Canvas** Average: 0.69 ms, Min: 0.58 ms, Max: 1.05 ms
**Skia Canvas** Average: 0.72 ms, Min: 0.52 ms, Max: 1.40 ms

Benchmark code https://github.com/gc/canvas-drawimage-benchmark
```
git clone https://github.com/gc/canvas-drawimage-benchmark.git
cd // yarn // npm install
node index.js
```

**Comment by rambo-panda** [comment]
![image](https://github.com/user-attachments/assets/953d8e80-dd08-4000-b649-31ce7179b5bc)

I think it is related to the fact that drawImage always copies image information.

**Comment by rambo-panda** [comment]
In the comparison of the three, the time consumption of drawImage differs the most, with nap-rs/canvas taking as long as 3 seconds. I suspect that the synchronous method is causing "queueing" in the main process.

**Comment by gc** [comment]
@Brooooooklyn Are you able to publish a new version so I can test? or is there a way I can test without a new version. thanks

**Comment by gc** [comment]
A big improvement. Thank you

NAPI Canvas Average: 10.68 ms, Min: 8.92 ms, Max: 20.96 ms
Node Canvas Average: 6.31 ms, Min: 5.30 ms, Max: 11.60 ms
Skia Canvas Average: 1.54 ms, Min: 1.35 ms, Max: 19.92 ms

**Comment by rambo-panda** [comment]
@gc @Brooooooklyn 
I found a serious risk of memory leakage during testing.

```
[129175840.177388] Killed process 11372 (node) total-vm:10889092kB, anon-rss:8374996kB, file-rss:28316kB, shmem-rss:0kB
```

this is my global env variable `NODE_OPTIONS=--max-old-space-size=8192`

![image](https://github.com/user-attachments/assets/b4a53c9b-16f4-413b-834d-6555640165b5)
