### ISSUE TITLE
Differences with skia-canvas?

### ISSUE THREAD

**Issue by xeoshow** [Brooooooklyn/canvas#883]
Hello, 

What are the main differences with skia-canvas as below? Thanks.

[https://github.com/samizdatco/skia-canvas](https://github.com/samizdatco/skia-canvas)

**Comment by Brooooooklyn** [comment]
@xeoshow this library is aim to provide zero system dependency experience and targets more platform.

**Comment by xeoshow** [comment]
This is extremely needed, since gyp c++ is really very very hard to use ...
