### ISSUE TITLE
PDF.js support

### ISSUE THREAD

**Issue by Brooooooklyn** [Brooooooklyn/canvas#931]

**Comment by GreenFlag31** [comment]
Could you be a bit more explicit ? There is no PDF.js support ?
When I try to use your lib with pdfjs.dist , I get : 
ebpack://pdf.js/src/display/canvas.js:261
        ^
Error: Value is non of these types `CanvasElement`, `SVGCanvas`, `Image`,

I wanted to replace node canvas with your lib, but unsucessfully. I'm on Node.js v20.
