### ISSUE TITLE
Wrong characters appear in font rendering

### ISSUE THREAD

**Issue by yhannn0814** [Brooooooklyn/canvas#961]
When I registered and used a font package with only English and numbers, but I filledText with Chinese, an abnormal string would be displayed. I expected to display a default font instead of error characters.

node v12.12.0
canvas: 2.11.2
macOs: 14.3.1 M1

**Comment by yhannn0814** [comment]
![BossHi-20241205201243](https://github.com/user-attachments/assets/a0682a57-f83f-410f-b9a7-6902951e155f)

**Comment by yhannn0814** [comment]
![Uploading 20241205201243.png…]()

**Comment by yhannn0814** [comment]
![Uploading 20241205201243.png…]()

**Comment by Brooooooklyn** [comment]
@yhannn0814 This is the expected behavior. This library will not automatically register fonts or automatically perform font fallback (as it does not rely on any third-party components). Therefore, if you want all content to render correctly, you need to accurately register and specify the fonts.

**Comment by yhannn0814** [comment]
> @yhannn0814 This is the expected behavior. This library will not automatically register fonts or automatically perform font fallback (as it does not rely on any third-party components). Therefore, if you want all content to render correctly, you need to accurately register and specify the fonts.
OK, got it.I'll go and improve my font package file first,but I still hope that it can support automatic font fallback later.
Thanks for your reply
