### ISSUE TITLE
Convertion with avif takes a huge amount of time

### ISSUE THREAD

**Issue by GreenFlag31** [Brooooooklyn/canvas#965]
Hi.

I'm using your dependency instead of node canvas with pdfjs-dist. I just want to report the huge amount of time required to convert a page of a PDF to an avif.

Reproduction:
```javascript
const viewport = page.getViewport({
  scale: 2,
});

const { width, height } = viewport;
const canvasAndContext = canvas.create(width, height);
const renderContext = {
  canvasContext: canvasAndContext.context,
  viewport,
};

await page.render(renderContext).promise;

// ...

canvasAndContext.canvas.toBuffer(`image/avif`),

// ... then await promises.writeFile(...)
```

It takes approx. 55 seconds to generate 4 PDF pages, while it takes 900ms to generate 4 pages with JPEG.

**Comment by Brooooooklyn** [comment]
Encoding lossless AVIF is very slow without hardware accelerators. You need to adjust the quality via `toBuffer()` avif config: https://github.com/Brooooooklyn/canvas/blob/main/src/avif.rs#L11-L21
